// <auto-generated />
using System;
using HSCSAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSCSAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HSCSAPI.Models.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<Guid>("AvailabilitySlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AvailabilitySlotId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Appointments.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("AvailabilitySlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilitySlotId");

                    b.HasIndex("DoctorId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("AvailabilitySlots", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Clinics.Clinic", b =>
                {
                    b.Property<Guid>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("AdminSecretaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBySuperAdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClinicId");

                    b.HasIndex("AdminSecretaryId")
                        .IsUnique()
                        .HasFilter("[AdminSecretaryId] IS NOT NULL");

                    b.HasIndex("CreatedBySuperAdminUserId");

                    b.ToTable("Clinics", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 7,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 1,
                            Name = "Patient"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Doctor"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Secretary"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "AuthorizedMember"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "LaboratoryTechnologist"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "RadiologyTechnologist"
                        });
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.UserVerificationCode", b =>
                {
                    b.Property<Guid>("UserVerificationCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserVerificationCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserVerificationCodes", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Laboratory.LabTestRequest", b =>
                {
                    b.Property<Guid>("LabTestRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LaboratoryTechnologistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResultMedicalFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LabTestRequestId");

                    b.HasIndex("LaboratoryTechnologistId");

                    b.HasIndex("ResultMedicalFileId");

                    b.ToTable("LabTestRequests", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.MedicalFiles.FileDownloadRequest", b =>
                {
                    b.Property<Guid>("FileDownloadRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicalFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PurposeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBySecretaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileDownloadRequestId");

                    b.HasIndex("MedicalFileId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReviewedBySecretaryId");

                    b.ToTable("FileDownloadRequests", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.MedicalFiles.MedicalFile", b =>
                {
                    b.Property<Guid>("MedicalFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedChecksum")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByDoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MedicalFileId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UploadedByDoctorId");

                    b.ToTable("MedicalFiles", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.AuthorizedMember", b =>
                {
                    b.Property<Guid>("AuthorizedMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorizedMemberId");

                    b.ToTable("AuthorizedMembers", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfessionalLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId");

                    b.HasIndex("ProfessionalLicenseNumber")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.LaboratoryTechnologist", b =>
                {
                    b.Property<Guid>("LaboratoryTechnologistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfessionalLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LaboratoryTechnologistId");

                    b.HasIndex("ProfessionalLicenseNumber")
                        .IsUnique();

                    b.ToTable("LaboratoryTechnologists", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatientId");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.RadiologyTechnologist", b =>
                {
                    b.Property<Guid>("RadiologyTechnologistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfessionalLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RadiologyTechnologistId");

                    b.HasIndex("ProfessionalLicenseNumber")
                        .IsUnique();

                    b.ToTable("RadiologyTechnologists", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Secretary", b =>
                {
                    b.Property<Guid>("SecretaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SecretaryId");

                    b.HasIndex("ClinicId");

                    b.ToTable("Secretaries", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Radiology.ImagingTestRequest", b =>
                {
                    b.Property<Guid>("ImagingTestRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RadiologyTechnologistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResultMedicalFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ImagingTestRequestId");

                    b.HasIndex("RadiologyTechnologistId");

                    b.HasIndex("ResultMedicalFileId");

                    b.ToTable("ImagingTestRequests", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Relations.Invite", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizedMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InviteId");

                    b.HasIndex("AuthorizedMemberId");

                    b.HasIndex("PatientId");

                    b.ToTable("Invites", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Relations.PatientAuthorizedMember", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizedMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AuthorizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PatientId", "AuthorizedMemberId");

                    b.HasIndex("AuthorizedMemberId");

                    b.ToTable("PatientAuthorizedMembers", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorizedMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReminderAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReminderText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ReminderId");

                    b.HasIndex("AuthorizedMemberId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Secretaries.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SecretaryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportId");

                    b.HasIndex("SecretaryId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Secretaries.ReportInformation", b =>
                {
                    b.Property<Guid>("ReportInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportInformationId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportInformations", (string)null);
                });

            modelBuilder.Entity("HSCSAPI.Models.Appointments.Appointment", b =>
                {
                    b.HasOne("HSCSAPI.Models.Appointments.AvailabilitySlot", "AvailabilitySlot")
                        .WithOne("Appointment")
                        .HasForeignKey("HSCSAPI.Models.Appointments.Appointment", "AvailabilitySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilitySlot");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HSCSAPI.Models.Appointments.AvailabilitySlot", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.Doctor", "Doctor")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HSCSAPI.Models.Clinics.Clinic", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.Secretary", "AdminSecretary")
                        .WithOne("ManagedClinic")
                        .HasForeignKey("HSCSAPI.Models.Clinics.Clinic", "AdminSecretaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSCSAPI.Models.Identity.User", "CreatedBySuperAdminUser")
                        .WithMany("CreatedClinics")
                        .HasForeignKey("CreatedBySuperAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminSecretary");

                    b.Navigation("CreatedBySuperAdminUser");
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.UserRole", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.UserVerificationCode", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Laboratory.LabTestRequest", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.LaboratoryTechnologist", "LaboratoryTechnologist")
                        .WithMany("LabTestRequests")
                        .HasForeignKey("LaboratoryTechnologistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSCSAPI.Models.MedicalFiles.MedicalFile", "ResultMedicalFile")
                        .WithMany("LabTestRequestsAsResult")
                        .HasForeignKey("ResultMedicalFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LaboratoryTechnologist");

                    b.Navigation("ResultMedicalFile");
                });

            modelBuilder.Entity("HSCSAPI.Models.MedicalFiles.FileDownloadRequest", b =>
                {
                    b.HasOne("HSCSAPI.Models.MedicalFiles.MedicalFile", "MedicalFile")
                        .WithMany("FileDownloadRequests")
                        .HasForeignKey("MedicalFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Patient", "Patient")
                        .WithMany("FileDownloadRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Secretary", "ReviewedBySecretary")
                        .WithMany("ReviewedFileDownloadRequests")
                        .HasForeignKey("ReviewedBySecretaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MedicalFile");

                    b.Navigation("Patient");

                    b.Navigation("ReviewedBySecretary");
                });

            modelBuilder.Entity("HSCSAPI.Models.MedicalFiles.MedicalFile", b =>
                {
                    b.HasOne("HSCSAPI.Models.Appointments.Appointment", "Appointment")
                        .WithMany("MedicalFiles")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Doctor", "UploadedByDoctor")
                        .WithMany("UploadedMedicalFiles")
                        .HasForeignKey("UploadedByDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("UploadedByDoctor");
                });

            modelBuilder.Entity("HSCSAPI.Models.Notifications.Notification", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.AuthorizedMember", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("AuthorizedMemberProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.AuthorizedMember", "AuthorizedMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Doctor", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.Doctor", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.LaboratoryTechnologist", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("LaboratoryTechnologistProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.LaboratoryTechnologist", "LaboratoryTechnologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Patient", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.Patient", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.RadiologyTechnologist", b =>
                {
                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("RadiologyTechnologistProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.RadiologyTechnologist", "RadiologyTechnologistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Secretary", b =>
                {
                    b.HasOne("HSCSAPI.Models.Clinics.Clinic", "Clinic")
                        .WithMany("Secretaries")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSCSAPI.Models.Identity.User", "User")
                        .WithOne("SecretaryProfile")
                        .HasForeignKey("HSCSAPI.Models.Profiles.Secretary", "SecretaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HSCSAPI.Models.Radiology.ImagingTestRequest", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.RadiologyTechnologist", "RadiologyTechnologist")
                        .WithMany("ImagingTestRequests")
                        .HasForeignKey("RadiologyTechnologistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSCSAPI.Models.MedicalFiles.MedicalFile", "ResultMedicalFile")
                        .WithMany("ImagingTestRequestsAsResult")
                        .HasForeignKey("ResultMedicalFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RadiologyTechnologist");

                    b.Navigation("ResultMedicalFile");
                });

            modelBuilder.Entity("HSCSAPI.Models.Relations.Invite", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.AuthorizedMember", "AuthorizedMember")
                        .WithMany("ReceivedInvites")
                        .HasForeignKey("AuthorizedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Patient", "Patient")
                        .WithMany("SentInvites")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedMember");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HSCSAPI.Models.Relations.PatientAuthorizedMember", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.AuthorizedMember", "AuthorizedMember")
                        .WithMany("Patients")
                        .HasForeignKey("AuthorizedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Patient", "Patient")
                        .WithMany("AuthorizedMembers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorizedMember");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HSCSAPI.Models.Reminders.Reminder", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.AuthorizedMember", "AuthorizedMember")
                        .WithMany("Reminders")
                        .HasForeignKey("AuthorizedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSCSAPI.Models.Profiles.Doctor", "Doctor")
                        .WithMany("Reminders")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSCSAPI.Models.Profiles.Patient", "Patient")
                        .WithMany("Reminders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedMember");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HSCSAPI.Models.Secretaries.Report", b =>
                {
                    b.HasOne("HSCSAPI.Models.Profiles.Secretary", "Secretary")
                        .WithMany("Reports")
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secretary");
                });

            modelBuilder.Entity("HSCSAPI.Models.Secretaries.ReportInformation", b =>
                {
                    b.HasOne("HSCSAPI.Models.Secretaries.Report", "Report")
                        .WithMany("ReportInformations")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("HSCSAPI.Models.Appointments.Appointment", b =>
                {
                    b.Navigation("MedicalFiles");
                });

            modelBuilder.Entity("HSCSAPI.Models.Appointments.AvailabilitySlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HSCSAPI.Models.Clinics.Clinic", b =>
                {
                    b.Navigation("Secretaries");
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HSCSAPI.Models.Identity.User", b =>
                {
                    b.Navigation("AuthorizedMemberProfile");

                    b.Navigation("CreatedClinics");

                    b.Navigation("DoctorProfile");

                    b.Navigation("LaboratoryTechnologistProfile");

                    b.Navigation("Notifications");

                    b.Navigation("PatientProfile");

                    b.Navigation("RadiologyTechnologistProfile");

                    b.Navigation("SecretaryProfile");

                    b.Navigation("UserRoles");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("HSCSAPI.Models.MedicalFiles.MedicalFile", b =>
                {
                    b.Navigation("FileDownloadRequests");

                    b.Navigation("ImagingTestRequestsAsResult");

                    b.Navigation("LabTestRequestsAsResult");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.AuthorizedMember", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("ReceivedInvites");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Reminders");

                    b.Navigation("UploadedMedicalFiles");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.LaboratoryTechnologist", b =>
                {
                    b.Navigation("LabTestRequests");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuthorizedMembers");

                    b.Navigation("FileDownloadRequests");

                    b.Navigation("Reminders");

                    b.Navigation("SentInvites");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.RadiologyTechnologist", b =>
                {
                    b.Navigation("ImagingTestRequests");
                });

            modelBuilder.Entity("HSCSAPI.Models.Profiles.Secretary", b =>
                {
                    b.Navigation("ManagedClinic");

                    b.Navigation("Reports");

                    b.Navigation("ReviewedFileDownloadRequests");
                });

            modelBuilder.Entity("HSCSAPI.Models.Secretaries.Report", b =>
                {
                    b.Navigation("ReportInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
